title: Eike Folkerts # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is me, Eike. Software Engineer from Germany, $currYYYY-1988 years old
  <br><br>
#  Second description 
#  <br><br>
  <a href="https://www.freelancermap.de/freelancer-verzeichnis/profile/entwicklung/387480-profil-eike-folkerts-software-engineer-senior-full-stack-developer-aus-norden.html">Freelancermap</a> 
  <a href="https://www.xing.com/profile/Eike_Folkerts2/">XING</a>
  <a href="https://www.linkedin.com/in/eike-folkerts-a93138195/">LinkedIn</a>
  #<a href=""></a>
  #<a href=""></a>
  
theme: jekyll-theme-minimal
google_analytics: UA-203298902-1
#google_analytics: G-P3SCEEXJXE
